include(../base.pri)
DESTDIR     = $$join(DESTDIR,,,/tools)
OBJECTS_DIR = $$join(OBJECTS_DIR,,,/tools/$$TARGET)
MOC_DIR     = $$join(MOC_DIR,,,/tools/$$TARGET)
RCC_DIR     = $$join(RCC_DIR,,,/tools/$$TARGET)
